### ISSUE TITLE
Review after date expiry is upcoming for user: richrace

### ISSUE THREAD

**Issue by AntonyBishop** [ministryofjustice/staff-device-dns-dhcp-infrastructure#162]
Hi there

The user @richrace has its access for this repository maintained in code here:
https://github.com/ministryofjustice/github-collaborators/blob/main/README.md#github-external-collaborators

The review_after date is due to expire within one month, please update this via a PR if they still require access.

If you have any questions, please post in #ask-operations-engineering on Slack.

**Comment by bagg3rs** [comment]
Thanks @AntonyBishop yes Rich will be finishing with us at that time.

**Comment by AntonyBishop** [comment]
Thanks @bagg3rs
