### ISSUE TITLE
Security: Restrict access to DHCP/DNS Portal to staff

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/staff-device-dns-dhcp-infrastructure#171]
User Story: As a… cloud ops team member, I would like to secure access to the dns-dhcp-admin portal to only MoJ staff So that our security posture of our portal is improved

Value / Purpose To help secure our DHCP/DNS portal.

Useful ContactsRich, Rachel

Additional Info
Do we need to include, third parties who are accessing from outside e.g. DOM1? CGI Helpdesk etc.

Definition of Done (DoD)DHCP/DNS Portal for all environmentshttps://dhcp-dns-admin.staff.service.justice.gov.uk/https://dhcp-dns-admin.prep.staff.service.justice.gov.uk/https://dhcp-dns-admin.dev.staff.service.justice.gov.uk/ 

Is only available from MoJ VPN-connected devices. 
[MoJO-VPN](https://github.com/ministryofjustice/moj-ip-addresses/blob/ec645eea5e9b963016f791fa1e019d193b065bbf/moj-cidr-addresses.yml#L273) 
[Alpha-VPN](https://github.com/ministryofjustice/moj-ip-addresses/blob/ec645eea5e9b963016f791fa1e019d193b065bbf/moj-cidr-addresses.yml#L291)

**Comment by mitchdawson1982** [comment]
Proposing to close this ticket and potentially create another to use entitlement once it becomes available. Seems Nimbus might be doing something on it but need clarity from Matt W also.
