### ISSUE TITLE
Security Groups - Unrestricted Access

### ISSUE THREAD

**Issue by mTouhid** [ministryofjustice/staff-device-dns-dhcp-infrastructure#174]
Several security groups have unrestricted access.

Groups:

- [x] staff-device-production-dhcp-admin-database
- [x] staff-device-production-dhcp-dhcp-container
- [x] staff-device-production-dhcp-dhcp-database-in
- [x] staff-device-production-dns-dns-container
- [x] staff-device-production-dns-dns-container

- [x] Update Trusted Advisor  

According to AWS security advisory report, these security groups need better IP restrictions.

**Comment by Gary-H9** [comment]
[`staff-device-production-dhcp-admin-database`](https://github.com/ministryofjustice/staff-device-dns-dhcp-infrastructure/blob/1141aacc3903cf58e244c3a4eccbbf7db7050969/modules/admin/security_groups.tf#L33) - internal DB, can this be locked down further, to only internal IPs/subnets.  
`staff-device-production-dhcp-dhcp-container` - 
[`staff-device-production-dhcp-dhcp-database-in`](https://github.com/ministryofjustice/staff-device-dns-dhcp-infrastructure/blob/1141aacc3903cf58e244c3a4eccbbf7db7050969/modules/dhcp/security_groups.tf#L82) similar to the DB above, in fact these two security groups look very similar. 
`staff-device-production-dns-dns-container` - looks to be fine, only applies to traffic out. Internal traffic is on a vpc basis. 
`staff-device-production-dns-dns-container` - same as above. 

Potential for a refactor here for the double mention of dhcp in `staff-device-production-dhcp-dhcp-container` and `staff-device-production-dhcp-dhcp-database-in`

**Comment by Gary-H9** [comment]
@emileswarts could we grab ten minutes with you to discuss this at some point please?

**Comment by Gary-H9** [comment]
All permitted. Updated Trusted Advisor
