### ISSUE TITLE
🤓 Add Terraform validate GH Action

### ISSUE THREAD

**Issue by wanieldilson** [ministryofjustice/staff-device-dns-dhcp-infrastructure#197]
### User Story

As a CloudOps engineer
I want to know if terraform code is valid 
So that I don't have to take manual steps to prove it is viable

### Value / Purpose

Save time with terraform PRs

### Definition of Done

Example
- [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by mitchdawson1982** [comment]
There is no real value duplicating work that is already carried out by the pipeline. This would make more sense if the deployment was carried out by a github action.

**Comment by mitchdawson1982** [comment]
There is no real value duplicating work that is already carried out by the pipeline. This would make more sense if the deployment was carried out by a github action.
