### ISSUE TITLE
🔓 Allow TCP port53 against MoJO-DNS

### ISSUE THREAD

**Issue by bagg3rs** [ministryofjustice/staff-device-dns-dhcp-infrastructure#203]
### User Story

As an Active Directory Domain Controller
I need to talk on TCP rather than UDP
So that I can do a lookup against MoJO-DNS

### Value / Purpose

Only UDP/53 is enabled which is causing name resolution to fail.
Close down old DNS servers and use MoJO-DNS

### Useful Contacts

Touhid, Rich, Dom Robinson

### Additional Information

There is an email chain in which Rich/Touhid are cc'd 
For testing of the change see slack thread [here](https://mojdt.slack.com/archives/C01J2L0SC0P/p1663075778077159)

### Definition of Done

- [ ] Another team member has reviewed

**Comment by mTouhid** [comment]
Pull requests are pending

**Comment by ASTRobinson** [comment]
awaiting feedback from the network team on how this should proceed.

**Comment by jennycasanova** [comment]
Network Team have confirmed they no longer want this change so this ticket can be pulled back and closed.
