### ISSUE TITLE
Azure AD Signing Certificates needs to be updated.

### ISSUE THREAD

**Issue by smjmoj** [ministryofjustice/staff-device-dns-dhcp-infrastructure#268]
`azure_federation_metadata_url            = "https://login.microsoftonline.com/0bb413d7-160d-4839-868a-f3d46537f6af/federationmetadata/2007-06/federationmetadata.xml?appid=ce2b341e-0cee-4fee-86a4-4d853ab6e5e7"`

`│ Error: updating Cognito Identity Provider (eu-west-2_TwUO4rgUL:Azure): InvalidParameterException: Signing certificates are expired
│ 
│   with module.authentication.aws_cognito_identity_provider.cognito_identity_provider[0],
│   on modules/authentication/main.tf line 53, in resource "aws_cognito_identity_provider" "cognito_identity_provider":
│   53: resource "aws_cognito_identity_provider" "cognito_identity_provider" {
│ 
╵
make: *** [Makefile:39: apply] Error 1`

**Comment by tomwells98** [comment]
This is reliant on another team to carry this out

**Comment by babatundek** [comment]
Ticket 27 unblocks this ticket

**Comment by darey-io** [comment]
This can now be closed. The certificate expiry issues no longer shows up.
