### ISSUE TITLE
🐛 Unhealthy container occurred on 12-10-23 at 7am UTC 

### ISSUE THREAD

**Issue by jamesgreen-moj** [ministryofjustice/staff-device-dns-dhcp-infrastructure#293]
### Describe the bug.

An ECS container task for the DNS service went unhealthy at 7am on the 12-10-23.

An investigation into how this container wen unhealthy needs to occur.

It has also came to our attention that the team did not get alerted to this unhealthy container. So this will also need to be investigated.

Useful links:

https://eu-west-2.console.aws.amazon.com/ec2/home?region=eu-west-2#TargetGroup:targetGroupArn=arn:aws:elasticloadbalancing:eu-west-2:037161842252:targetgroup/staff-device-production-dns/53bd525bd9a1ef0e

https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#metricsV2?graph=~(metrics~(~(~'AWS*2fNetworkELB~'UnHealthyHostCount~'TargetGroup~'targetgroup*2fstaff-device-production-dns*2f53bd525bd9a1ef0e~'LoadBalancer~'net*2fstaff-device-production-dns*2f754e69ecf996b619~(label~'staff-device-production-dns~region~'eu-west-2)))~period~60~region~'eu-west-2~stat~'Maximum~title~'Unhealthy*20Hosts*20*28Maximum*29~yAxis~(left~(min~0))~start~'2023-10-12T06*3a55*3a00.000Z~end~'2023-10-12T07*3a05*3a59.000Z~view~'timeSeries~stacked~false)

https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logsV2:log-groups/log-group/staff-device-production-dns-server-log-group/log-events$3Fstart$3D1697092200000$26end$3D1697094000000

A ticket to AWS has also been raised: 

Case ID 14047008101 

### Expected Behaviour

- Containers should not go unhealthy
- Team should be alerted in the event a container does go unhealthy 

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by juddin927** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBems2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--079ae86c3cba3121aab28df789379d8ecf8ed058/Screenshot%202023-10-16%20at%2011.52.15.png)

**Comment by juddin927** [comment]
You reached out to us as you noticed an unhealthy target in "UnhealthyHostCount" metric of NLB but ECS didn’t deregister the unhealthy target from the target group and didn’t replace it with a new healthy target. You need help to troubleshoot this issue.

I started my investigation by checking NLB metrics and confirmed that NLB marked the target as unhealthy at 2023-10-12 07:01:00 UTC. Then, I reviewed the ECS Service events for this timestamp and could see there was a service scale-up event that updated the service's desired count from 3 to 4 but other than that I didn’t see any events in ECS Service events history for this timestamp.

Next, I reviewed the NLB metrics for the above timestamp again. This time I checked the "HealthyHostCount" metrics with "Maximum" statistics and I didn’t find any drop in the metrics. At the same time when I checked the "UnHealthyHostCount" metrics with "Minimum" statistic I didn't see any spikes in the metrics. The value was constantly zero.[1]

When load balancer does a health checks on the targets from the multiple host, the health checks should fail for all the host from which health check request is receiving. When any of the request from one of the hosts get failed in that case "UnHealthyHostCount" metrics with Maximum statistics will go above to zero which may be a false positive as other hosts are able to mark the target as healthy. At the same time if you check the metrics with Minimum statistics it will show zero. To avoid any false positives, its recommended to monitor the metrics for "UnHealthyHostCount" with the "Minimum" statistics.

From an ECS perspective:
- ECS Service will do a periodic `DescribeTargetHealth` API against the NLB to verify target health.
- Please note that the target health reported are consensus of the overall health as seen by the NLB.
- From the observed behavior, when ECS performs `DescribeTargetHealth` API against the NLB, all targets were healthy so the ECS service remained in a steady state (no action required).

Having said above, could you please confirm if you observed any performance issues related to your application at the time of the issue? Please check and get back to us.
