### ISSUE TITLE
Fix connection and public IP issues and add documentation.

### ISSUE THREAD

**Issue by smjmoj** [ministryofjustice/staff-device-dns-dhcp-infrastructure#310]
During the development of the NACs RDS Bastion feature, it was noted that this implementation had some issues.

1. associate_public_ip_address | this was incorrectly set.
2. security_group_ids | the VPC endpoinst security group had been omitted.
3. ssm_session_manager_endpoints | for the services required some logic as they are shared with the load testing bastion.

In order to create an easy engineer experience some additional outputs have been added for consistency across the two projects.

The documentation has been added.

**Comment by NNavickas1** [comment]
ticket #601 raised for follow on work
